
services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sga_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  usuarios-service:
    build: ./usuarios-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sga_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      mysql-db:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway  # La carpeta donde está tu API Gateway
    ports:
      - "8080:8080"  # El puerto expuesto para que accedas desde tu navegador
    depends_on:
      - usuarios-service  # Se asegura que usuarios-service esté listo