server:
  port: 8080  # El API Gateway escuchará aquí

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: usuarios-service
          uri: http://usuarios-service:8080  # Nombre del servicio Docker + puerto
          predicates:
            - Path=/api/usuarios/**
        
        - id: inventarios-service
          uri: http://inventarios-service:8080  # Nombre del servicio Docker + puerto
          predicates:
            - Path=/api/inventarios/**

        - id: ventas-service
          uri: http://ventas-service:8080  # Nombre del servicio Docker + puerto
          predicates:
            - Path=/api/ventas/**