spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://api-gateway.local"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: usuarios-service
          uri: http://usuarios-service.usuarios.svc.cluster.local:80
          predicates:
            - Path=/api/usuarios/**
          

        - id: inventarios-service
          uri: http://inventarios-service.inventarios.svc.cluster.local:80
          predicates:
            - Path=/api/inventarios/**
          

        - id: ventas-service
          uri: http://ventas-service.ventas.svc.cluster.local:80
          predicates:
            - Path=/api/ventas/**
          

        - id: alertas-service
          uri: http://alertas-service.alertas.svc.cluster.local:80
          predicates:
            - Path=/api/alertas/**
          

        - id: reportes-service
          uri: http://reportes-service.reportes.svc.cluster.local:80
          predicates:
            - Path=/api/reportes/**
          

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true