server:
  port: 8080  # El API Gateway escuchará aquí


spring:
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: ${USUARIOS_SERVICE_URL}  # Nombre del servicio Docker + puerto
          predicates:
            - Path=/api/usuarios/**
        
        - id: inventarios-service
          uri: ${INVENTARIOS_SERVICE_URL}  # Nombre del servicio Docker + puerto
          predicates:
            - Path=/api/inventarios/**

        - id: ventas-service
          uri: ${VENTAS_SERVICE_URL}  # Nombre del servicio Docker + puerto
          predicates:
            - Path=/api/ventas/**