name: Build, Test, and Deploy Docker Containers

on:
  push:
    branches:
      - main  # O la rama que uses para despliegue

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3: Construir el microservicio de usuarios
      - name: Build Usuarios Service with Maven
        working-directory: ./backend/usuarios-service # Especifica el directorio del microservicio
        run: mvn clean package -DskipTests

      # Paso 4: Construir el API Gateway con Maven
      - name: Build API Gateway with Maven
        working-directory: ./backend/api-gateway # Especifica el directorio del microservicio
        run: mvn clean package -DskipTests

      # Paso 5: Configurar Docker y Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 6: Cacheo de Docker (opcional)
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Paso 7: Construir imágenes Docker
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Paso 8: Levantar los contenedores Docker (en segundo plano)
      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d

      # Paso 8: Realizar pruebas de integración (si las tienes)
      - name: Run integration tests
        run: mvn verify

      # Paso 10: Desplegar o detener los contenedores Docker
      - name: Clean up Docker containers
        run: |
          docker-compose down
