name: Build, Test, and Deploy Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construcción de servicios usando matrix
      - name: Build microservices with Maven
        run: |
          for dir in usuarios-service api-gateway inventarios-service; do
            echo "🔧 Building $dir"
            mvn -f ./backend/$dir/pom.xml clean package -DskipTests
          done

      # Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache para Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build imágenes Docker
      - name: Build Docker images
        working-directory: ./backend
        run: docker-compose build

      # (Opcional) Bajar servicios después del build
      - name: Clean up Docker containers
        working-directory: ./backend
        run: docker-compose down
