name: CI/CD - Usuarios Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/usuarios-service/**'

jobs:
  build-usuarios-service:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Paso 1: Clonar el código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 2.5: Obtener hash del último commit en la carpeta del microservicio
      - name: Get last commit hash for usuarios-service
        id: get_hash
        run: echo "IMAGE_TAG=$(git log -n 1 --pretty=format:%h -- backend/usuarios-service)" >> $GITHUB_ENV

      # Paso 3: Construir el microservicio con Maven
      - name: Build usuarios-service with Maven
        run: mvn -f backend/usuarios-service/pom.xml clean package -DskipTests

      # Paso 4: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 5: Cache de capas Docker
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        
      # Paso 6: Login a Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Paso 7: Build
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/usuarios-service:latest \
                      -t ${{ secrets.DOCKERHUB_USERNAME }}/usuarios-service:${{ env.IMAGE_TAG }} \
                      backend/usuarios-service

      # Paso 8: Push
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/usuarios-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/usuarios-service:${{ env.IMAGE_TAG }}


      # Paso 9: Clonar el repo de despliegue
      - name: Checkout deploy repo
        uses: actions/checkout@v4
        with:
          repository: PaulaMilla/prueba_gps-deploy
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          path: deploy-repo

      # Paso 10: Actualizar el manifiesto con el nuevo tag
      - name: Update deployment manifest image tag
        run: |
          sed -i "s|\(image: .*/usuarios-service:\).*|\1${{ env.IMAGE_TAG }}|" deploy-repo/usuarios-service/deployment.yaml

      # Paso 11: Commit y push al repo de despliegue
      - name: Commit and push changes
        run: |
          cd deploy-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add usuarios-service/deployment.yaml
          git commit -m "Update usuarios-service image tag to ${{ env.IMAGE_TAG }}"
          git push